name: Continuous Deployment
on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Code CheckOut
              uses: actions/checkout@v3

            - name: Build Docker Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest .
