name: Continuous Deployment
on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Code CheckOut
              uses: actions/checkout@v3

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                
            - name: Set up Docker Build
              uses: docker/setup-buildx-action@v2

            - name: Remove old container if it exists
              run: |
                docker rm -f myapp 2>/dev/null || true

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/my-node-app-cicd:${{ github.sha }}

            - name: Done
              run: echo "Image pushed to Docker Hub!"

            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    echo "📦 Updating package lists..."
                    sudo apt-get update -y

                    echo "Checking docker installation"
                    if command -v docker &> /dev/null; then
                        echo "Docker installation found"
                    else
                        echo "Docker installation not found. Installing Docker."
                        curl https://get.docker.com | bash
                        exit 1
                    fi

                    sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app-cicd:${{ github.sha }}
                    sudo docker stop myapp || true && docker rm myapp || true
                    sudo docker run -d --name myapp -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app-cicd:${{ github.sha }}